### PR TITLE
[Windows][melodic-devel] Follow catkin guide to update the install path

### PR DESCRIPTION
**Pull request by seanyen**
Follow `catkin` guide to update the install path for better portability.

* https://docs.ros.org/api/catkin/html/howto/format1/building_libraries.html
* https://docs.ros.org/api/catkin/html/howto/format1/building_executables.html

### CODE REVIEW

**Review by meyerj — APPROVED** [review]
LGTM, thanks.

Some other, more visible catkin documentation still recommends to install all targets with
```cmake
install(TARGETS ${PROJECT_NAME}
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)
```
and does not make a difference between executables and libraries, like:
- https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/templates/CMakeLists.txt.in
- http://wiki.ros.org/catkin/CMakeLists.txt#Optional_Step:_Specifying_Installable_Targets

**Comment by seanyen** [comment]
@meyerj Thanks for bringing those links to my attention. I will contact the owners and see if I can update it too.

**Comment by seanyen** [comment]
@meyerj Just FYI, both locations are now updated to be aligned with `catkin` user guide. And let me know anything I should do to make this pull request move forward. Thanks!

**Comment by meyerj** [comment]
> @meyerj Just FYI, both locations are now updated to be aligned with `catkin` user guide. And let me know anything I should do to make this pull request move forward. Thanks!

Perfect, thanks!

**Pull request merged**
