### PR TITLE
Add service to gazebo gps sensor to set reference geopose

### PR DESCRIPTION
**Pull request by MCFurry**
This PR implements a set_reference_geopose service for the gazebo_ros_gps plugin.

Similar to the SetDatum service in robot localization's navsat_transform node, it allows for changing the geographic reference pose.

We found this especially useful in simulations that need resets on new tasks for example, or simulation that travel far from the origin. But also for simulations to set this from the ROS framework, instead of hard-coding it in xml's.

### CODE REVIEW

**Comment by MCFurry** [comment]
Subtle ping here ;-)

**Comment by StefanFabian** [comment]
What's the use case for setting the reference pose during simulation rather than at launch?

**Comment by MCFurry** [comment]
Thanks for your comment.

We have a few:
 - 'resetting' a simulation. We for example have some 'digital twins' running our software stack in simulation. They automatically start a task upon receival, but sometimes these tasks are defined in another country which means the current reference gps position in simulation should be reset. (Ideally runtime instead of restarting the software stack).
 - Traveling large distances in simulation. For some applications our simulation robot could travel really long distances and hence it requires such a reference reset.
 - Simply having a 'dynamic' interface for setting the reference position. The suggested service call is almost identical to the SetDatum service in [Navsat-transform](https://github.com/cra-ros-pkg/robot_localization/blob/noetic-devel/src/navsat_transform.cpp). So in principle every call to this node's service would in simulation logically follow a call to the suggested setGeopose service. 

And I imagine there are more usecases where maybe on starting the simulation, the ideal reference gps position is simply not known yet and hence a dynamic way of setting it is very useful.

**Comment by StefanFabian** [comment]
Looks good to me. Thank you for your contribution!

**Comment by MCFurry** [comment]
Thx for that! Any chance this package can have a new release such that we have it in the next sync?

**Comment by StefanFabian** [comment]
Sorry didn't have time earlier. I'm preparing a release now.

**Comment by MCFurry** [comment]
Thanks a lot!

**Pull request merged**
