### PR TITLE
[hector_gazebo_plugins] fix missing dependencies

### PR DESCRIPTION
**Pull request by furushchev**
This is necessary for generating ROS messages

### CODE REVIEW

**Comment by furushchev** [comment]
@meyerj How do you think of this PR?

**Comment by meyerj** [comment]
You are absolutely right. I will merge this patch to indigo-devel and jade-devel. Thanks!

**Comment by meyerj** [comment]
Also merged to jade-devel in f622397.

**Comment by furushchev** [comment]
@meyerj Thanks for merging!

**Pull request merged**
